

name: PHP CI/CD


on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]


jobs:
  build:
    
    runs-on: ubuntu-latest

    
    services:
      mariadb:
        image: mariadb:10.7
        
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }} 
          MYSQL_DATABASE: task_tracker
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        
        options: "--health-cmd=mysqladmin ping -h 127.0.0.1 -u root -p'${{ secrets.DB_ROOT_PASSWORD }}' --health-interval=10s --health-timeout=5s --health-retries=5"

    
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
    
      
      - name: Checkout Code
        uses: actions/checkout@v4

      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, curl, json, pdo_mysql 
          coverage: none

      
      - name: Cache Composer Dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php-version }}-composer-
      
      
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        

      
      - name: Wait for Database to be ready
        run: |
          max_retries=10
          for i in $(seq 1 $max_retries); do
            if mysql -h 127.0.0.1 -u testuser -ptestpassword task_tracker -e "SELECT 1" > /dev/null 2>&1; then
              echo "Database is up and running!"
              exit 0
            fi
            echo "Waiting for Database (Attempt $i/$max_retries)..."
            sleep 3
          done
          echo "Database service failed to start."
          exit 1